<?php

/**
 * @file North Carolina File Table Formatter module.
 */

/**
 * Implements hook_field_formatter_info().
 */
function nc_file_table_formatter_field_formatter_info() {
  return array(
    'nc_file_table_formatter' => array(
      'label' => t('Display file contents as table'),
      'field types' => array('file'),
      'settings'  => array(
        'header' => FALSE,
      ),
    ),
  );
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function nc_file_table_formatter_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $element = array();

  $element['header'] = array(
    '#type'           => 'checkbox',
    '#title'          => t('Files include a header row'),
    '#description'    => t('If checked first row will be displayed formatted as a table header'),
    '#default_value'  => $settings['header'],
  );
  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function nc_file_table_formatter_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $summary = t('Files include a header row: @header', array(
    '@header' => empty($settings['header']) ? t('No') : t('Yes'),
  ));
  return $summary;
}

/**
 * Implements hook_field_formatter_view().
 */
function nc_file_table_formatter_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {

  $element = array();

  $includes_header = !empty($display['settings']['header']);
  foreach ($items as $delta => $item) {
    $table_data = nc_file_table_formatter_get_table_data_from_file($item, $includes_header);
    $table_data['title'] = !empty($item['description']) ? $item['description'] : '';

    // Add additional info that may be helpful for alter implementations.
    $table_data['item'] = $item;
    $table_data['entity'] = $entity;
    $table_data['entity_type'] = $entity_type;
    $table_data['field'] = $field;
    $table_data['display'] = $display;
    $table_data['instance'] = $instance;
    $table_data['langcode'] = $langcode;

    drupal_alter('nc_file_table_formatter', $table_data);

    if (!empty($table_data['header']) && !empty($table_data['rows'])) {
      $element[$delta]['#markup'] = theme('nc_file_table_formatter_table', array('data' => $table_data));
    }
    else {
      $element[$delta]['#markup'] = NULL;
    }

  }
  return $element;
}

function nc_file_table_formatter_get_table_data_from_file($file, $includes_header = FALSE) {
  if (is_array($file)) {
    $file = (object) $file;
  }

  $data = array();


    // Read the file
  $fhandle = fopen($file->uri, 'r');
  if (!empty($fhandle)) {
    $contents = file_get_contents($file->uri);
  }
  fclose($fhandle);

  if (!empty($contents)) {
        // Parse as CSV
    $data = str_getcsv($contents, "\n");
    foreach ($data as &$row) {
      $row = str_getcsv($row);
    }
  }

  $result = array(
    'header' => NULL,
    'rows' => NULL,
  );

  if (!empty($data)) {
    // Handle header.
    if ($includes_header) {
      $result['header'] = array_shift($data);
    }
    $result['rows'] = $data;
  }

  return $result;
}

/**
 * Implements hook_theme().
 */
function nc_file_table_formatter_theme() {
  return array(
    'nc_file_table_formatter_table' => array(
      'variables' => array('data' => NULL),
    )
  );
}

/**
 * Theme function for the file table formatter.
 *
 * @param $variables
 * @return string
 */
function theme_nc_file_table_formatter_table($variables) {
  $output = '';
  // Reformat arrays for theme_table;
  $header = NULL;
  if (!empty($variables['data']['header'])) {
    foreach ($variables['data']['header'] as $col) {
      $header[] = array('data' => $col);
    }
  }

  $rows = array();
  if (!empty($variables['data']['rows'])) {
    foreach ($variables['data']['rows'] as $col) {
      $rows[] = array('data' => $col);
    }
  }

  if (!empty($rows) || !empty($header)) {
    if (!empty($variables['data']['title'])) {
      $output .= '<h2 class="file-table-title">' . check_plain($variables['data']['title']) . '</h2>';
    }
    $output .= theme('tablefield_view', array(
      'header' => $header,
      'rows' => $rows,
    )
  );
    $output .= '<a href="' . file_create_url($variables['data']['item']['uri']) . '">Export Table Data</a>';
  }

  return $output;
}
