<?php
/**
 * @file
 * File for the NC Base Theme settings Module.
 */

/**
 * Validates the svg upload setting.
 */
function _nc_base_theme_logo_svg_upload_validate(&$element, &$form_state) {
  $validators = array('file_validate_extensions' => array('svg'));
  // Check for a new uploaded logo.
  $file = file_save_upload('logo_svg_upload', $validators);
  if (isset($file)) {
    // File upload was attempted.
    if ($file) {
      // Put the temporary file in form_values so we can save it on submit.
      $form_state['values']['logo_svg_upload'] = $file;
      $filename = file_unmanaged_copy($file->uri);
      $form_state['values']['logo_svg_path'] = $filename;
    }
    else {
      // File upload failed.
      form_set_error('logo_svg_upload', t('The svg logo could not be uploaded.'));
    }
  }
}

/**
 * Validates the svg path setting.
 */
function _nc_base_theme_logo_svg_path_validate(&$element, &$form_state) {
  if (!empty($form_state['values']['logo_svg_path'])) {
    $path = _system_theme_settings_validate_path($form_state['values']['logo_svg_path']);
    if (!$path) {
      form_set_error('logo_svg_path', t('The logo svg path is invalid.'));
    }
    else {
      $ext = substr($path, -4);
      if ($ext != '.svg') {
        form_set_error('logo_svg_path', t('The logo svg path must be a path to a svg file.'));
      }
    }
  }
}

/**
 * Validates the footer upload setting.
 */
function _nc_base_theme_logo_footer_upload_validate(&$element, &$form_state) {
  $validators = array('file_validate_extensions' => array('jpeg jpg gif png svg'));
  // Check for a new uploaded logo.
  $file = file_save_upload('logo_footer_upload', $validators);
  if (isset($file)) {
    // File upload was attempted.
    if ($file) {
      // Put the temporary file in form_values so we can save it on submit.
      $form_state['values']['logo_footer_upload'] = $file;
      $filename = file_unmanaged_copy($file->uri);
      $form_state['values']['logo_footer_path'] = $filename;
    }
    else {
      // File upload failed.
      form_set_error('logo_footer_upload', t('The footer logo could not be uploaded.'));
    }
  }
}

/**
 * Validates the footer path setting.
 */
function _nc_base_theme_logo_footer_path_validate(&$element, &$form_state) {
  if (!empty($form_state['values']['logo_footer_path'])) {
    $path = _system_theme_settings_validate_path($form_state['values']['logo_footer_path']);
    if (!$path) {
      form_set_error('logo_footer_path', t('The logo footer path is invalid.'));
    }
    else {
      $ext = explode('.', $path);
      $ext = end($ext);
      if (!in_array($ext, array('svg', 'gif', 'png', 'jpg', 'jpeg'))) {
        form_set_error('logo_footer_path', t('The logo footer path must be a path to a valid image file'));
      }
    }
  }
}

/**
 * Validates the favicon upload setting.
 */
function _nc_base_theme_favicon_upload_validate(&$element, &$form_state) {
  $validators = array('file_validate_extensions' => array('png'));
  // Check for a new uploaded favicon.
  $file = file_save_upload('favicon_upload', $validators);

  if (isset($file)) {
    // File upload was attempted.
    if ($file) {
      // Put the temporary file in form_values so we can save it on submit.
      $form_state['values']['favicon_upload'] = $file;
      $filename = file_unmanaged_copy($file->uri);
      $form_state['values']['favicon_path'] = $filename;

      $favicon_variants = nc_favicon_style_list();
      foreach($favicon_variants as $variant => $favicon_type) {
        $new_favicon_uri = str_replace('.png', '-' . $variant . '.png', $filename);
        if (!file_exists($new_favicon_uri))
        $styled_url = image_style_create_derivative(image_style_load($variant), $filename, $new_favicon_uri);
        $styled_url_final = file_create_url(str_replace('.png', '-' . $variant . '.png', $filename));

      }
    }
    else {
      // File upload failed.
      form_set_error('favicon_upload', t('The favicon could not be uploaded.'));
    }
  }
}

/**
 * Validates the favicon path setting.
 */
function _nc_base_theme_favicon_path_validate(&$element, &$form_state) {
  if (!empty($form_state['values']['favicon_path'])) {
    $path = _system_theme_settings_validate_path($form_state['values']['favicon_path']);
    if (!$path) {
      form_set_error('favicon_path', t('The favicon path is invalid.'));
    }
    else {
      $ext = explode('.', $path);
      $ext = end($ext);
      if (!in_array($ext, array('png'))) {
        form_set_error('favicon_path', t('The path path must be a path to a valid .png image file'));
      }
    }
  }
}