<?php
/**
 * @file
 * NC Fields module file.
 */

/**
 * Implements hook_image_default_styles().
 */
function nc_fields_image_default_styles() {
  $styles = array();

  // Exported image style: event-detail.
  $styles['main-image'] = array(
    'name' => 'main-image',
    'label' => 'main-image',
    'effects' => array(
      1 => array(
        'label' => 'Scale and crop',
        'help' => 'Scale and crop will maintain the aspect-ratio of the original image, then crop the larger dimension. This is most useful for creating perfectly square thumbnails without stretching the image.',
        'effect callback' => 'image_scale_and_crop_effect',
        'dimensions callback' => 'image_resize_dimensions',
        'form callback' => 'image_resize_form',
        'summary theme' => 'image_resize_summary',
        'module' => 'image',
        'name' => 'image_scale_and_crop',
        'data' => array(
          'width' => 740,
          'height' => 416,
        ),
        'weight' => 1,
      ),
    ),
  );

  return $styles;
}


/**
 * Implements hook_theme().
 */
function nc_fields_theme($existing, $type, $theme, $path) {
  $items = array();
  $path = drupal_get_path('module', 'nc_fields');
  $items['nc_term_label'] = array(
    'arguments' => array(
      'term' => NULL,
      'type' => 'simple',
      'language' => LANGUAGE_NONE,
    ),
    'file' => 'nc_fields.theme.inc',
    'path' => $path,
  );
  $items['nc_file_detail'] = array(
    'arguments' => array(
      'file' => NULL,
      'node' => NULL,
      'language' => LANGUAGE_NONE,
    ),
    'file' => 'nc_fields.theme.inc',
    'path' => $path,
  );
  $items['nc_date'] = array(
    'arguments' => array(
      'date' => time(),
      'label' => t('Release Date'),
      'language' => LANGUAGE_NONE,
    ),
    'file' => 'nc_fields.theme.inc',
    'path' => $path,
  );
  return $items;
}

/**
 * Implements hook_field_formatter_info().
 */
function nc_fields_field_formatter_info() {
  return array(
    // Display terms as an ABT styled label.
    'nc_fields_term_formatter_simple' => array(
      'label' => t('NC Term Label'),
      'field types' => array('taxonomy_term_reference'),
    ),
    'nc_fields_file_formatter_detail' => array(
      'label' => t('NC File Detail'),
      'field types' => array('file'),
    ),
    'nc_fields_date_formatter' => array(
      'label' => t('NC Date'),
      'field types' => array('date', 'datestamp', 'datetime'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function nc_fields_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  // ABT#620 - Noticed that the group parent displays even if there
  // are no items selected (empty array). This should fix that.
  if (!$items || !isset($items)) {
    return;
  }

  switch ($display['type']) {
    case 'nc_fields_term_formatter_simple':
      foreach ($items as $delta => $item) {
        $term = taxonomy_term_load($item['tid']);
        $element[$delta] = theme('nc_term_label', array(
          'term' => $term,
          'type' => 'simple',
          'language' => $langcode)
        );
      }
      break;

    case 'nc_fields_file_formatter_detail':
      foreach ($items as $delta => $item) {
        $element[$delta] = theme('nc_file_detail', array(
          'file' => $item,
          'node' => $entity,
          'language' => $langcode)
        );
      }
      break;

    case 'nc_fields_date_formatter':
      foreach ($items as $delta => $item) {
        $element[$delta] = theme('nc_date', array(
          'date' => $item,
          'label' => $instance['label'],
          'language' => $langcode)
        );
      }
      break;

  }
  $element['#attached']['css'] = array(
    drupal_get_path('module', 'nc_fields') . '/nc_fields.css',
  );

  return $element;
}

/**
 * Implements hook_form_system_theme_settings_alter().
 *
 * This is being used to add a new settings to the theme/appearance
 * where administrative users can toggle between the default
 * and alternate document icons.
 *
 * See: http://www.digitalstyle.nc.gov/section-1.html#section-1.4.2
 */
function nc_fields_form_alter(&$form, $form_state) {
  // Ensure we're in the theme settings form.
  if (isset($form['var']) &&
    isset($form['var']['#value']) &&
    $form['var']['#value'] == 'theme_nc_base_theme_settings'
  ) {
    // The setting is stored with the theme.
    $theme = variable_get('theme_default', 'nc_base_theme');
    // Add the Document icon dropdown.
    $form['nc_base_theme_settings']['document_type_icon_fieldset'] = array(
      '#type' => 'fieldset',
      '#title' => t('Document Type Icons'),
      '#description' => t('Document Type Icons are the icons displayed in association with various document types (i.e. doc, xls, image, etc)'),
    );
    $form['nc_base_theme_settings']['document_type_icon_fieldset']['document_type_icon_style'] = array(
      '#type' => 'select',
      '#title' => t('Document Type Icons Style'),
      '#default_value' => theme_get_setting('document_type_icon_style', $theme),
      '#description' => t('Select an icon style for use with document types.'),
      '#options' => array(
        '' => t("Default"),
        'alt' => t("Alt"),
      ),
    );
  }
}

/**
 * Get the style modifier associated with the theme settings.
 *
 * @return string
 *   Return the icon class modifier (i.e. -alt).
 */
function nc_fields_get_document_type_icon_style() {
  // This is the code that checks theme settings
  // to see which icon version to use.
  $icon_style = '';

  // The setting is stored with the theme.
  if (($theme = variable_get('theme_default', 'nc_base_theme')) != NULL) {
    $icon_setting = theme_get_setting('document_type_icon_style', $theme);

    // For safety/sanitization
    switch ($icon_setting) {
      case 'alt':
        $icon_style = '-alt';
        break;

      case 'default':
      default:
        $icon_style = '';
        break;

    }
  }

  return $icon_style;
}

/**
 * Convert a filemime type to a CSS class.
 *
 * @param string $mimetype
 *   File mimetype.
 *
 * @return string
 *   Return a string representing a CSS class to be used to theme the file icon.
 */
function nc_fields_file_mime_to_doctype($mimetype) {
  // Initialize the doctype.
  $doctype = array(
    'icon' => '',
    'type' => '',
  );

  // This is the code that checks theme settings
  // to see which icon version to use.
  $icon_style = nc_fields_get_document_type_icon_style();

  // Convert mime type into a simplified string representation.
  $type = nc_fields_file_detect_class_from_mime_type($mimetype);

  // Update doctype based on simplified type representation.
  switch ($type) {
    case 'document':
      $doctype['icon'] = 'icon-doctype-doc' . $icon_style;
      $doctype['type'] = 'DOC';
      break;

    case 'pdf':
      $doctype['icon'] = 'icon-doctype-pdf' . $icon_style;
      $doctype['type'] = 'PDF';
      break;

    case 'image':
      $doctype['icon'] = 'icon-doctype-photo' . $icon_style;
      $doctype['type'] = 'IMAGE';
      break;

    case 'spreadsheet':
      $doctype['icon'] = 'icon-doctype-xls' . $icon_style;
      $doctype['type'] = 'XLS';
      break;

    case 'presentation':
      $doctype['icon'] = 'icon-doctype-ppt' . $icon_style;
      $doctype['type'] = 'PPT';
      break;

    case 'text':
    default:
      $doctype['icon'] = 'icon-doctype-text' . $icon_style;
      $doctype['type'] = 'TEXT';
      break;
  }

  return $doctype;
}

/**
 * Match the given MIME type to a given classification such as ...
 *
 *  - image
 *  - text
 *  - pdf
 *  - spreadsheet
 *  - presentation
 *  - document
 *  - default
 * .
 *
 * @param string $mimetype
 *   MIME type.
 *
 * @return string
 *   Return a simplified type (classification) of file
 */
function nc_fields_file_detect_class_from_mime_type($mimetype) {
  // The mimeMap is an array of key value pairs
  // The keys represent return values (i.e. simplified classes)
  // The values are an array of text patterns (for use with preg_match),
  // which can be used to map MIME to class.
  $mime_map = array(

    // Matches images.
    'image' => array(
      '/^image\/(.)*/',
    ),

    // Matches text files.
    'text' => array(
      '/^text\/(.)*/',
    ),

    // Matches PDFs (.pdf).
    'pdf' => array(
      '/(.)*\/(.)*(pdf)+(.)*/',
    ),

    // Matches spreadsheets (Excel .xls, .xlxs, etc).
    'spreadsheet' => array(
      '/^application\/(.)*excel(.)*/',
      '/^application\/vnd.openxmlformats-officedocument.spreadsheetml(.)*/',
    ),

    // Matches presentations (Powerpoint .ppt, .pptx, etc).
    'presentation' => array(
      '/^application\/vnd.ms-powerpoint(.)*/',
      '/^application\/vnd.openxmlformats-officedocument.presentationml(.)*/',
    ),

    // Matches documents (Word docs like .doc, .docx, etc).
    'document' => array(
      '/^application\/msword*/',
      '/^application\/vnd.ms-word(.)*/',
      '/^application\/vnd.openxmlformats-officedocument.wordprocessingml(.)*/',
    ),

    // This is here to catch anything not matched by the previous patterns.
    'default' => array(
      '/(.)*/',
    ),
  );

  // Search through the defined patterns, and return any matches.
  foreach ($mime_map as $key => $patterns) {
    foreach ($patterns as $pattern) {
      if (preg_match($pattern, $mimetype) === 1) {
        return $key;
      }
    }
  }

  // Ohgodhowdidthisgethereiamnotgoodwithcomputer.
  // Seriously, you shouldn't get here, but this is for safety.
  return 'default';
}

/**
 * Implements hook_preprocess_field().
 */
function nc_fields_preprocess_field(&$variables) {
  switch ($variables['element']['#formatter']) {
    case 'nc_fields_date_formatter':
      $variables['classes_array'][] = 'nc-date-field';
      break;

    case 'nc_fields_file_formatter_detail':
      $variables['classes_array'][] = 'nc-file-field';
      break;

    case 'nc_fields_term_formatter_simple':
      $variables['classes_array'][] = 'nc-term-field';
      break;
  }
}

/**
 * Returns an array of NC icon classes for use platform wide.
 */
function nc_fields_icons() {
  return array(
    'icon-nc-medical' => 'icon-nc-medical',
    'icon-nc-deaf-blind' => 'icon-nc-deaf-blind',
    'icon-nc-vision' => 'icon-nc-vision',
    'icon-nc-veteran' => 'icon-nc-veteran',
    'icon-nc-seniors' => 'icon-nc-seniors',
    'icon-nc-campfire' => 'icon-nc-campfire',
    'icon-nc-baby' => 'icon-nc-baby',
    'icon-nc-mental' => 'icon-nc-mental',
    'icon-nc-no-home' => 'icon-nc-no-home',
    'icon-nc-handicap' => 'icon-nc-handicap',
    'icon-nc-compass' => 'icon-nc-compass',
    'icon-nc-donate' => 'icon-nc-donate',
    'icon-nc-eco-house' => 'icon-nc-eco-house',
    'icon-nc-faces-culture' => 'icon-nc-faces-culture',
    'icon-nc-family' => 'icon-nc-family',
    'icon-nc-government-building' => 'icon-nc-government-building',
    'icon-nc-group-people' => 'icon-nc-group-people',
    'icon-nc-justice' => 'icon-nc-justice',
    'icon-nc-libraries' => 'icon-nc-libraries',
    'icon-nc-newspaper' => 'icon-nc-newspaper',
    'icon-nc-online-service' => 'icon-nc-online-service',
    'icon-nc-pie-chart' => 'icon-nc-pie-chart',
    'icon-nc-service-budget' => 'icon-nc-service-budget',
    'icon-nc-service-families' => 'icon-nc-service-families',
    'icon-pinterest' => 'icon-pinterest',
    'icon-leaf' => 'icon-leaf',
    'icon-youtube2' => 'icon-youtube2',
    'icon-flickr' => 'icon-flickr',
    'icon-googleplus' => 'icon-googleplus',
    'icon-facebook' => 'icon-facebook',
    'icon-instagram' => 'icon-instagram',
    'icon-twitter' => 'icon-twitter',
    'icon-feed' => 'icon-feed',
    'icon-youtube' => 'icon-youtube',
    'icon-3d-rotation' => 'icon-3d-rotation',
    'icon-accessibility' => 'icon-accessibility',
    'icon-account-balance-wallet' => 'icon-account-balance-wallet',
    'icon-account-box' => 'icon-account-box',
    'icon-account-circle' => 'icon-account-circle',
    'icon-add-shopping-cart' => 'icon-add-shopping-cart',
    'icon-alarm' => 'icon-alarm',
    'icon-alarm-add' => 'icon-alarm-add',
    'icon-alarm-off' => 'icon-alarm-off',
    'icon-alarm-on' => 'icon-alarm-on',
    'icon-android' => 'icon-android',
    'icon-announcement' => 'icon-announcement',
    'icon-aspect-ratio' => 'icon-aspect-ratio',
    'icon-assessment' => 'icon-assessment',
    'icon-assignment' => 'icon-assignment',
    'icon-assignment-ind' => 'icon-assignment-ind',
    'icon-assignment-late' => 'icon-assignment-late',
    'icon-assignment-return' => 'icon-assignment-return',
    'icon-assignment-returned' => 'icon-assignment-returned',
    'icon-assignment-turned-in' => 'icon-assignment-turned-in',
    'icon-autorenew' => 'icon-autorenew',
    'icon-backup' => 'icon-backup',
    'icon-book' => 'icon-book',
    'icon-bookmark' => 'icon-bookmark',
    'icon-bookmark-outline' => 'icon-bookmark-outline',
    'icon-bug-report' => 'icon-bug-report',
    'icon-cached' => 'icon-cached',
    'icon-class' => 'icon-class',
    'icon-credit-card' => 'icon-credit-card',
    'icon-dashboard' => 'icon-dashboard',
    'icon-delete' => 'icon-delete',
    'icon-description' => 'icon-description',
    'icon-dns' => 'icon-dns',
    'icon-done' => 'icon-done',
    'icon-done-all' => 'icon-done-all',
    'icon-event' => 'icon-event',
    'icon-exit-to-app' => 'icon-exit-to-app',
    'icon-explore' => 'icon-explore',
    'icon-extension' => 'icon-extension',
    'icon-favorite' => 'icon-favorite',
    'icon-favorite-outline' => 'icon-favorite-outline',
    'icon-find-in-page' => 'icon-find-in-page',
    'icon-find-replace' => 'icon-find-replace',
    'icon-flip-to-back' => 'icon-flip-to-back',
    'icon-flip-to-front' => 'icon-flip-to-front',
    'icon-get-app' => 'icon-get-app',
    'icon-grade' => 'icon-grade',
    'icon-group-work' => 'icon-group-work',
    'icon-help2' => 'icon-help2',
    'icon-history' => 'icon-history',
    'icon-home' => 'icon-home',
    'icon-https' => 'icon-https',
    'icon-input' => 'icon-input',
    'icon-launch' => 'icon-launch',
    'icon-list' => 'icon-list',
    'icon-lock' => 'icon-lock',
    'icon-lock-open' => 'icon-lock-open',
    'icon-lock-outline' => 'icon-lock-outline',
    'icon-loyalty' => 'icon-loyalty',
    'icon-markunread-mailbox' => 'icon-markunread-mailbox',
    'icon-note-add' => 'icon-note-add',
    'icon-open-in-browser' => 'icon-open-in-browser',
    'icon-open-in-new' => 'icon-open-in-new',
    'icon-open-with' => 'icon-open-with',
    'icon-pageview' => 'icon-pageview',
    'icon-payment' => 'icon-payment',
    'icon-perm-data-setting' => 'icon-perm-data-setting',
    'icon-perm-identity' => 'icon-perm-identity',
    'icon-perm-media' => 'icon-perm-media',
    'icon-perm-phone-msg' => 'icon-perm-phone-msg',
    'icon-perm-scan-wifi' => 'icon-perm-scan-wifi',
    'icon-picture-in-picture' => 'icon-picture-in-picture',
    'icon-polymer' => 'icon-polymer',
    'icon-print' => 'icon-print',
    'icon-question-answer' => 'icon-question-answer',
    'icon-receipt' => 'icon-receipt',
    'icon-redeem' => 'icon-redeem',
    'icon-reorder' => 'icon-reorder',
    'icon-report-problem' => 'icon-report-problem',
    'icon-restore' => 'icon-restore',
    'icon-room' => 'icon-room',
    'icon-schedule' => 'icon-schedule',
    'icon-settings' => 'icon-settings',
    'icon-settings-applications' => 'icon-settings-applications',
    'icon-settings-backup-restore' => 'icon-settings-backup-restore',
    'icon-settings-bluetooth' => 'icon-settings-bluetooth',
    'icon-settings-cell' => 'icon-settings-cell',
    'icon-settings-ethernet' => 'icon-settings-ethernet',
    'icon-settings-input-antenna' => 'icon-settings-input-antenna',
    'icon-settings-input-component' => 'icon-settings-input-component',
    'icon-settings-input-composite' => 'icon-settings-input-composite',
    'icon-settings-input-hdmi' => 'icon-settings-input-hdmi',
    'icon-settings-input-svideo' => 'icon-settings-input-svideo',
    'icon-settings-overscan' => 'icon-settings-overscan',
    'icon-settings-phone' => 'icon-settings-phone',
    'icon-settings-power' => 'icon-settings-power',
    'icon-settings-remote' => 'icon-settings-remote',
    'icon-settings-voice' => 'icon-settings-voice',
    'icon-shop' => 'icon-shop',
    'icon-shop-two' => 'icon-shop-two',
    'icon-shopping-basket' => 'icon-shopping-basket',
    'icon-shopping-cart' => 'icon-shopping-cart',
    'icon-speaker-notes' => 'icon-speaker-notes',
    'icon-spellcheck' => 'icon-spellcheck',
    'icon-stars' => 'icon-stars',
    'icon-store' => 'icon-store',
    'icon-subject' => 'icon-subject',
    'icon-supervisor-account' => 'icon-supervisor-account',
    'icon-swap-horiz' => 'icon-swap-horiz',
    'icon-swap-vert' => 'icon-swap-vert',
    'icon-tab' => 'icon-tab',
    'icon-tab-unselected' => 'icon-tab-unselected',
    'icon-theaters' => 'icon-theaters',
    'icon-thumb-down' => 'icon-thumb-down',
    'icon-thumb-up' => 'icon-thumb-up',
    'icon-thumbs-up-down' => 'icon-thumbs-up-down',
    'icon-toc' => 'icon-toc',
    'icon-today' => 'icon-today',
    'icon-track-changes' => 'icon-track-changes',
    'icon-translate' => 'icon-translate',
    'icon-trending-down' => 'icon-trending-down',
    'icon-trending-neutral' => 'icon-trending-neutral',
    'icon-trending-up' => 'icon-trending-up',
    'icon-turned-in' => 'icon-turned-in',
    'icon-turned-in-not' => 'icon-turned-in-not',
    'icon-verified-user' => 'icon-verified-user',
    'icon-view-agenda' => 'icon-view-agenda',
    'icon-view-array' => 'icon-view-array',
    'icon-view-carousel' => 'icon-view-carousel',
    'icon-view-column' => 'icon-view-column',
    'icon-view-day' => 'icon-view-day',
    'icon-view-headline' => 'icon-view-headline',
    'icon-view-list' => 'icon-view-list',
    'icon-view-module' => 'icon-view-module',
    'icon-view-quilt' => 'icon-view-quilt',
    'icon-view-stream' => 'icon-view-stream',
    'icon-view-week' => 'icon-view-week',
    'icon-visibility' => 'icon-visibility',
    'icon-visibility-off' => 'icon-visibility-off',
    'icon-work' => 'icon-work',
    'icon-warning2' => 'icon-warning2',
    'icon-album' => 'icon-album',
    'icon-av-timer' => 'icon-av-timer',
    'icon-closed-caption' => 'icon-closed-caption',
    'icon-equalizer' => 'icon-equalizer',
    'icon-explicit' => 'icon-explicit',
    'icon-fast-forward' => 'icon-fast-forward',
    'icon-fast-rewind' => 'icon-fast-rewind',
    'icon-games' => 'icon-games',
    'icon-hearing' => 'icon-hearing',
    'icon-high-quality' => 'icon-high-quality',
    'icon-loop' => 'icon-loop',
    'icon-mic' => 'icon-mic',
    'icon-movie' => 'icon-movie',
    'icon-new-releases' => 'icon-new-releases',
    'icon-not-interested' => 'icon-not-interested',
    'icon-pause' => 'icon-pause',
    'icon-pause-circle-outline' => 'icon-pause-circle-outline',
    'icon-play-arrow' => 'icon-play-arrow',
    'icon-play-circle-outline' => 'icon-play-circle-outline',
    'icon-playlist-add' => 'icon-playlist-add',
    'icon-queue' => 'icon-queue',
    'icon-radio' => 'icon-radio',
    'icon-recent-actors' => 'icon-recent-actors',
    'icon-repeat' => 'icon-repeat',
    'icon-repeat-one' => 'icon-repeat-one',
    'icon-replay' => 'icon-replay',
    'icon-shuffle' => 'icon-shuffle',
    'icon-skip-next' => 'icon-skip-next',
    'icon-skip-previous' => 'icon-skip-previous',
    'icon-snooze' => 'icon-snooze',
    'icon-stop' => 'icon-stop',
    'icon-subtitles' => 'icon-subtitles',
    'icon-surround-sound' => 'icon-surround-sound',
    'icon-video-collection' => 'icon-video-collection',
    'icon-videocam' => 'icon-videocam',
    'icon-videocam-off' => 'icon-videocam-off',
    'icon-volume-down' => 'icon-volume-down',
    'icon-volume-mute' => 'icon-volume-mute',
    'icon-volume-off' => 'icon-volume-off',
    'icon-volume-up' => 'icon-volume-up',
    'icon-web' => 'icon-web',
    'icon-business' => 'icon-business',
    'icon-call' => 'icon-call',
    'icon-call-end' => 'icon-call-end',
    'icon-call-made' => 'icon-call-made',
    'icon-call-merge' => 'icon-call-merge',
    'icon-call-missed' => 'icon-call-missed',
    'icon-call-received' => 'icon-call-received',
    'icon-call-split' => 'icon-call-split',
    'icon-chat' => 'icon-chat',
    'icon-clear-all' => 'icon-clear-all',
    'icon-comment' => 'icon-comment',
    'icon-contacts' => 'icon-contacts',
    'icon-dialer-sip' => 'icon-dialer-sip',
    'icon-dialpad' => 'icon-dialpad',
    'icon-email' => 'icon-email',
    'icon-forum' => 'icon-forum',
    'icon-import-export' => 'icon-import-export',
    'icon-invert-colors-off' => 'icon-invert-colors-off',
    'icon-invert-colors-on' => 'icon-invert-colors-on',
    'icon-live-help' => 'icon-live-help',
    'icon-location-off' => 'icon-location-off',
    'icon-location-on' => 'icon-location-on',
    'icon-message' => 'icon-message',
    'icon-no-sim' => 'icon-no-sim',
    'icon-phone' => 'icon-phone',
    'icon-portable-wifi-off' => 'icon-portable-wifi-off',
    'icon-ring-volume' => 'icon-ring-volume',
    'icon-stay-current-landscape' => 'icon-stay-current-landscape',
    'icon-stay-current-portrait' => 'icon-stay-current-portrait',
    'icon-stay-primary-landscape' => 'icon-stay-primary-landscape',
    'icon-stay-primary-portrait' => 'icon-stay-primary-portrait',
    'icon-swap-calls' => 'icon-swap-calls',
    'icon-textsms' => 'icon-textsms',
    'icon-voicemail' => 'icon-voicemail',
    'icon-vpn-key' => 'icon-vpn-key',
    'icon-add' => 'icon-add',
    'icon-add-box' => 'icon-add-box',
    'icon-add-circle' => 'icon-add-circle',
    'icon-add-circle-outline' => 'icon-add-circle-outline',
    'icon-archive' => 'icon-archive',
    'icon-backspace' => 'icon-backspace',
    'icon-block' => 'icon-block',
    'icon-clear' => 'icon-clear',
    'icon-content-copy' => 'icon-content-copy',
    'icon-content-cut' => 'icon-content-cut',
    'icon-content-paste' => 'icon-content-paste',
    'icon-create' => 'icon-create',
    'icon-drafts' => 'icon-drafts',
    'icon-filter-list' => 'icon-filter-list',
    'icon-flag' => 'icon-flag',
    'icon-forward' => 'icon-forward',
    'icon-gesture' => 'icon-gesture',
    'icon-inbox' => 'icon-inbox',
    'icon-link' => 'icon-link',
    'icon-mail' => 'icon-mail',
    'icon-markunread' => 'icon-markunread',
    'icon-redo' => 'icon-redo',
    'icon-remove' => 'icon-remove',
    'icon-remove-circle' => 'icon-remove-circle',
    'icon-remove-circle-outline' => 'icon-remove-circle-outline',
    'icon-reply' => 'icon-reply',
    'icon-reply-all' => 'icon-reply-all',
    'icon-save' => 'icon-save',
    'icon-select-all' => 'icon-select-all',
    'icon-send' => 'icon-send',
    'icon-sort' => 'icon-sort',
    'icon-text-format' => 'icon-text-format',
    'icon-undo' => 'icon-undo',
    'icon-access-alarm' => 'icon-access-alarm',
    'icon-access-alarms' => 'icon-access-alarms',
    'icon-access-time' => 'icon-access-time',
    'icon-add-alarm' => 'icon-add-alarm',
    'icon-battery-alert' => 'icon-battery-alert',
    'icon-battery-charging-full' => 'icon-battery-charging-full',
    'icon-battery-full' => 'icon-battery-full',
    'icon-battery-std' => 'icon-battery-std',
    'icon-battery-unknown' => 'icon-battery-unknown',
    'icon-bluetooth' => 'icon-bluetooth',
    'icon-bluetooth-connected' => 'icon-bluetooth-connected',
    'icon-bluetooth-disabled' => 'icon-bluetooth-disabled',
    'icon-bluetooth-searching' => 'icon-bluetooth-searching',
    'icon-brightness-auto' => 'icon-brightness-auto',
    'icon-brightness-high' => 'icon-brightness-high',
    'icon-brightness-low' => 'icon-brightness-low',
    'icon-brightness-medium' => 'icon-brightness-medium',
    'icon-data-usage' => 'icon-data-usage',
    'icon-developer-mode' => 'icon-developer-mode',
    'icon-devices' => 'icon-devices',
    'icon-dvr' => 'icon-dvr',
    'icon-gps-fixed' => 'icon-gps-fixed',
    'icon-gps-not-fixed' => 'icon-gps-not-fixed',
    'icon-gps-off' => 'icon-gps-off',
    'icon-location-disabled' => 'icon-location-disabled',
    'icon-location-searching' => 'icon-location-searching',
    'icon-network-cell' => 'icon-network-cell',
    'icon-network-wifi' => 'icon-network-wifi',
    'icon-nfc' => 'icon-nfc',
    'icon-now-wallpaper' => 'icon-now-wallpaper',
    'icon-now-widgets' => 'icon-now-widgets',
    'icon-screen-lock-landscape' => 'icon-screen-lock-landscape',
    'icon-screen-lock-portrait' => 'icon-screen-lock-portrait',
    'icon-screen-lock-rotation' => 'icon-screen-lock-rotation',
    'icon-screen-rotation' => 'icon-screen-rotation',
    'icon-sd-storage' => 'icon-sd-storage',
    'icon-settings-system-daydream' => 'icon-settings-system-daydream',
    'icon-signal-cellular-4-bar' => 'icon-signal-cellular-4-bar',
    'icon-signal-cellular-connected-no-internet-4-bar' => 'icon-signal-cellular-connected-no-internet-4-bar',
    'icon-signal-cellular-no-sim' => 'icon-signal-cellular-no-sim',
    'icon-signal-cellular-null' => 'icon-signal-cellular-null',
    'icon-signal-cellular-off' => 'icon-signal-cellular-off',
    'icon-signal-wifi-4-bar' => 'icon-signal-wifi-4-bar',
    'icon-signal-wifi-off' => 'icon-signal-wifi-off',
    'icon-storage' => 'icon-storage',
    'icon-usb' => 'icon-usb',
    'icon-wifi-lock' => 'icon-wifi-lock',
    'icon-wifi-tethering' => 'icon-wifi-tethering',
    'icon-attach-file' => 'icon-attach-file',
    'icon-attach-money' => 'icon-attach-money',
    'icon-border-all' => 'icon-border-all',
    'icon-border-bottom' => 'icon-border-bottom',
    'icon-border-clear' => 'icon-border-clear',
    'icon-border-color' => 'icon-border-color',
    'icon-border-horizontal' => 'icon-border-horizontal',
    'icon-border-inner' => 'icon-border-inner',
    'icon-border-left' => 'icon-border-left',
    'icon-border-outer' => 'icon-border-outer',
    'icon-border-right' => 'icon-border-right',
    'icon-border-style' => 'icon-border-style',
    'icon-border-top' => 'icon-border-top',
    'icon-border-vertical' => 'icon-border-vertical',
    'icon-format-align-center' => 'icon-format-align-center',
    'icon-format-align-justify' => 'icon-format-align-justify',
    'icon-format-align-left' => 'icon-format-align-left',
    'icon-format-align-right' => 'icon-format-align-right',
    'icon-format-bold' => 'icon-format-bold',
    'icon-format-clear' => 'icon-format-clear',
    'icon-format-color-fill' => 'icon-format-color-fill',
    'icon-format-color-reset' => 'icon-format-color-reset',
    'icon-format-color-text' => 'icon-format-color-text',
    'icon-format-indent-decrease' => 'icon-format-indent-decrease',
    'icon-format-indent-increase' => 'icon-format-indent-increase',
    'icon-format-italic' => 'icon-format-italic',
    'icon-format-line-spacing' => 'icon-format-line-spacing',
    'icon-format-list-bulleted' => 'icon-format-list-bulleted',
    'icon-format-list-numbered' => 'icon-format-list-numbered',
    'icon-format-paint' => 'icon-format-paint',
    'icon-format-quote' => 'icon-format-quote',
    'icon-format-size' => 'icon-format-size',
    'icon-format-strikethrough' => 'icon-format-strikethrough',
    'icon-format-textdirection-l-to-r' => 'icon-format-textdirection-l-to-r',
    'icon-format-textdirection-r-to-l' => 'icon-format-textdirection-r-to-l',
    'icon-format-underlined' => 'icon-format-underlined',
    'icon-functions' => 'icon-functions',
    'icon-insert-chart' => 'icon-insert-chart',
    'icon-insert-comment' => 'icon-insert-comment',
    'icon-insert-drive-file' => 'icon-insert-drive-file',
    'icon-insert-emoticon' => 'icon-insert-emoticon',
    'icon-insert-invitation' => 'icon-insert-invitation',
    'icon-insert-link' => 'icon-insert-link',
    'icon-insert-photo' => 'icon-insert-photo',
    'icon-merge-type' => 'icon-merge-type',
    'icon-mode-comment' => 'icon-mode-comment',
    'icon-mode-edit' => 'icon-mode-edit',
    'icon-publish' => 'icon-publish',
    'icon-vertical-align-bottom' => 'icon-vertical-align-bottom',
    'icon-vertical-align-center' => 'icon-vertical-align-center',
    'icon-vertical-align-top' => 'icon-vertical-align-top',
    'icon-wrap-text' => 'icon-wrap-text',
    'icon-attachment' => 'icon-attachment',
    'icon-cloud' => 'icon-cloud',
    'icon-cloud-circle' => 'icon-cloud-circle',
    'icon-cloud-done' => 'icon-cloud-done',
    'icon-cloud-download' => 'icon-cloud-download',
    'icon-cloud-off' => 'icon-cloud-off',
    'icon-cloud-queue' => 'icon-cloud-queue',
    'icon-cloud-upload' => 'icon-cloud-upload',
    'icon-file-download' => 'icon-file-download',
    'icon-file-upload' => 'icon-file-upload',
    'icon-folder' => 'icon-folder',
    'icon-folder-open' => 'icon-folder-open',
    'icon-folder-shared' => 'icon-folder-shared',
    'icon-cast' => 'icon-cast',
    'icon-cast-connected' => 'icon-cast-connected',
    'icon-computer' => 'icon-computer',
    'icon-desktop-mac' => 'icon-desktop-mac',
    'icon-desktop-windows' => 'icon-desktop-windows',
    'icon-dock' => 'icon-dock',
    'icon-gamepad' => 'icon-gamepad',
    'icon-headset' => 'icon-headset',
    'icon-headset-m' => 'icon-headset-m',
    'icon-keyboard' => 'icon-keyboard',
    'icon-keyboard-arrow-down' => 'icon-keyboard-arrow-down',
    'icon-keyboard-arrow-left' => 'icon-keyboard-arrow-left',
    'icon-keyboard-arrow-right' => 'icon-keyboard-arrow-right',
    'icon-keyboard-arrow-up' => 'icon-keyboard-arrow-up',
    'icon-keyboard-backspace' => 'icon-keyboard-backspace',
    'icon-keyboard-capslock' => 'icon-keyboard-capslock',
    'icon-keyboard-control' => 'icon-keyboard-control',
    'icon-keyboard-hide' => 'icon-keyboard-hide',
    'icon-keyboard-return' => 'icon-keyboard-return',
    'icon-keyboard-tab' => 'icon-keyboard-tab',
    'icon-keyboard-voice' => 'icon-keyboard-voice',
    'icon-laptop' => 'icon-laptop',
    'icon-laptop-chromebook' => 'icon-laptop-chromebook',
    'icon-laptop-mac' => 'icon-laptop-mac',
    'icon-laptop-windows' => 'icon-laptop-windows',
    'icon-memory' => 'icon-memory',
    'icon-mouse' => 'icon-mouse',
    'icon-phone-android' => 'icon-phone-android',
    'icon-phone-iphone' => 'icon-phone-iphone',
    'icon-phonelink' => 'icon-phonelink',
    'icon-phonelink-off' => 'icon-phonelink-off',
    'icon-security' => 'icon-security',
    'icon-sim-card' => 'icon-sim-card',
    'icon-smartphone' => 'icon-smartphone',
    'icon-speaker' => 'icon-speaker',
    'icon-tablet' => 'icon-tablet',
    'icon-tablet-android' => 'icon-tablet-android',
    'icon-tablet-mac' => 'icon-tablet-mac',
    'icon-tv' => 'icon-tv',
    'icon-watch' => 'icon-watch',
    'icon-add-to-photos' => 'icon-add-to-photos',
    'icon-adjust' => 'icon-adjust',
    'icon-assistant-photo' => 'icon-assistant-photo',
    'icon-audiotrack' => 'icon-audiotrack',
    'icon-blur-circular' => 'icon-blur-circular',
    'icon-blur-linear' => 'icon-blur-linear',
    'icon-blur-off' => 'icon-blur-off',
    'icon-blur-on' => 'icon-blur-on',
    'icon-brightness-1' => 'icon-brightness-1',
    'icon-brightness-2' => 'icon-brightness-2',
    'icon-brightness-3' => 'icon-brightness-3',
    'icon-brightness-4' => 'icon-brightness-4',
    'icon-brightness-5' => 'icon-brightness-5',
    'icon-brightness-6' => 'icon-brightness-6',
    'icon-brightness-7' => 'icon-brightness-7',
    'icon-brush' => 'icon-brush',
    'icon-camera' => 'icon-camera',
    'icon-camera-alt' => 'icon-camera-alt',
    'icon-camera-front' => 'icon-camera-front',
    'icon-camera-rear' => 'icon-camera-rear',
    'icon-camera-roll' => 'icon-camera-roll',
    'icon-center-focus-strong' => 'icon-center-focus-strong',
    'icon-center-focus-weak' => 'icon-center-focus-weak',
    'icon-collections' => 'icon-collections',
    'icon-color-lens' => 'icon-color-lens',
    'icon-colorize' => 'icon-colorize',
    'icon-compare' => 'icon-compare',
    'icon-control-point' => 'icon-control-point',
    'icon-control-point-duplicate' => 'icon-control-point-duplicate',
    'icon-crop-3-2' => 'icon-crop-3-2',
    'icon-crop-5-4' => 'icon-crop-5-4',
    'icon-crop-7-5' => 'icon-crop-7-5',
    'icon-crop-16-9' => 'icon-crop-16-9',
    'icon-crop' => 'icon-crop',
    'icon-crop-din' => 'icon-crop-din',
    'icon-crop-free' => 'icon-crop-free',
    'icon-crop-landscape' => 'icon-crop-landscape',
    'icon-crop-original' => 'icon-crop-original',
    'icon-crop-portrait' => 'icon-crop-portrait',
    'icon-crop-square' => 'icon-crop-square',
    'icon-details' => 'icon-details',
    'icon-edit' => 'icon-edit',
    'icon-exposure' => 'icon-exposure',
    'icon-exposure-minus-1' => 'icon-exposure-minus-1',
    'icon-exposure-minus-2' => 'icon-exposure-minus-2',
    'icon-exposure-plus-1' => 'icon-exposure-plus-1',
    'icon-exposure-plus-2' => 'icon-exposure-plus-2',
    'icon-exposure-zero' => 'icon-exposure-zero',
    'icon-filter-1' => 'icon-filter-1',
    'icon-filter-2' => 'icon-filter-2',
    'icon-filter-3' => 'icon-filter-3',
    'icon-filter-4' => 'icon-filter-4',
    'icon-filter-5' => 'icon-filter-5',
    'icon-filter-6' => 'icon-filter-6',
    'icon-filter-7' => 'icon-filter-7',
    'icon-filter-8' => 'icon-filter-8',
    'icon-filter-9' => 'icon-filter-9',
    'icon-filter-9-plus' => 'icon-filter-9-plus',
    'icon-filter' => 'icon-filter',
    'icon-filter-b-and-w' => 'icon-filter-b-and-w',
    'icon-filter-center-focus' => 'icon-filter-center-focus',
    'icon-filter-drama' => 'icon-filter-drama',
    'icon-filter-frames' => 'icon-filter-frames',
    'icon-filter-hdr' => 'icon-filter-hdr',
    'icon-filter-none' => 'icon-filter-none',
    'icon-filter-tilt-shift' => 'icon-filter-tilt-shift',
    'icon-filter-vintage' => 'icon-filter-vintage',
    'icon-flare' => 'icon-flare',
    'icon-flash-auto' => 'icon-flash-auto',
    'icon-flash-off' => 'icon-flash-off',
    'icon-flash-on' => 'icon-flash-on',
    'icon-flip' => 'icon-flip',
    'icon-gradient' => 'icon-gradient',
    'icon-grain' => 'icon-grain',
    'icon-grid-off' => 'icon-grid-off',
    'icon-grid-on' => 'icon-grid-on',
    'icon-hdr-off' => 'icon-hdr-off',
    'icon-hdr-on' => 'icon-hdr-on',
    'icon-hdr-strong' => 'icon-hdr-strong',
    'icon-hdr-weak' => 'icon-hdr-weak',
    'icon-healing' => 'icon-healing',
    'icon-image' => 'icon-image',
    'icon-image-aspect-ratio' => 'icon-image-aspect-ratio',
    'icon-iso' => 'icon-iso',
    'icon-landscape' => 'icon-landscape',
    'icon-leak-add' => 'icon-leak-add',
    'icon-leak-remove' => 'icon-leak-remove',
    'icon-lens' => 'icon-lens',
    'icon-looks-3' => 'icon-looks-3',
    'icon-looks-4' => 'icon-looks-4',
    'icon-looks-5' => 'icon-looks-5',
    'icon-looks-6' => 'icon-looks-6',
    'icon-looks' => 'icon-looks',
    'icon-looks-one' => 'icon-looks-one',
    'icon-looks-two' => 'icon-looks-two',
    'icon-loupe' => 'icon-loupe',
    'icon-movie-creation' => 'icon-movie-creation',
    'icon-nature' => 'icon-nature',
    'icon-nature-people' => 'icon-nature-people',
    'icon-navigate-before' => 'icon-navigate-before',
    'icon-navigate-next' => 'icon-navigate-next',
    'icon-palette' => 'icon-palette',
    'icon-panorama' => 'icon-panorama',
    'icon-panorama-horizontal' => 'icon-panorama-horizontal',
    'icon-panorama-vertical' => 'icon-panorama-vertical',
    'icon-panorama-wide-angle' => 'icon-panorama-wide-angle',
    'icon-photo' => 'icon-photo',
    'icon-photo-album' => 'icon-photo-album',
    'icon-photo-camera' => 'icon-photo-camera',
    'icon-photo-library' => 'icon-photo-library',
    'icon-portrait' => 'icon-portrait',
    'icon-remove-red-eye' => 'icon-remove-red-eye',
    'icon-rotate-left' => 'icon-rotate-left',
    'icon-rotate-right' => 'icon-rotate-right',
    'icon-slideshow' => 'icon-slideshow',
    'icon-straighten' => 'icon-straighten',
    'icon-style' => 'icon-style',
    'icon-switch-camera' => 'icon-switch-camera',
    'icon-switch-video' => 'icon-switch-video',
    'icon-tag-faces' => 'icon-tag-faces',
    'icon-texture' => 'icon-texture',
    'icon-timelapse' => 'icon-timelapse',
    'icon-timer-3' => 'icon-timer-3',
    'icon-timer-10' => 'icon-timer-10',
    'icon-timer' => 'icon-timer',
    'icon-timer-off' => 'icon-timer-off',
    'icon-tonality' => 'icon-tonality',
    'icon-transform' => 'icon-transform',
    'icon-tune' => 'icon-tune',
    'icon-wb-auto' => 'icon-wb-auto',
    'icon-wb-cloudy' => 'icon-wb-cloudy',
    'icon-wb-incandescent' => 'icon-wb-incandescent',
    'icon-wb-sunny' => 'icon-wb-sunny',
    'icon-beenhere' => 'icon-beenhere',
    'icon-directions' => 'icon-directions',
    'icon-directions-bike' => 'icon-directions-bike',
    'icon-directions-bus' => 'icon-directions-bus',
    'icon-directions-car' => 'icon-directions-car',
    'icon-directions-ferry' => 'icon-directions-ferry',
    'icon-directions-subway' => 'icon-directions-subway',
    'icon-directions-transit' => 'icon-directions-transit',
    'icon-directions-walk' => 'icon-directions-walk',
    'icon-flight' => 'icon-flight',
    'icon-hotel' => 'icon-hotel',
    'icon-layers' => 'icon-layers',
    'icon-layers-clear' => 'icon-layers-clear',
    'icon-local-airport' => 'icon-local-airport',
    'icon-local-atm' => 'icon-local-atm',
    'icon-local-attraction' => 'icon-local-attraction',
    'icon-local-bar' => 'icon-local-bar',
    'icon-local-cafe' => 'icon-local-cafe',
    'icon-local-car-wash' => 'icon-local-car-wash',
    'icon-local-convenience-store' => 'icon-local-convenience-store',
    'icon-local-drink' => 'icon-local-drink',
    'icon-local-florist' => 'icon-local-florist',
    'icon-local-gas-station' => 'icon-local-gas-station',
    'icon-local-grocery-store' => 'icon-local-grocery-store',
    'icon-local-hospital' => 'icon-local-hospital',
    'icon-local-hotel' => 'icon-local-hotel',
    'icon-local-laundry-service' => 'icon-local-laundry-service',
    'icon-local-library' => 'icon-local-library',
    'icon-local-mall' => 'icon-local-mall',
    'icon-local-movies' => 'icon-local-movies',
    'icon-local-offer' => 'icon-local-offer',
    'icon-local-parking' => 'icon-local-parking',
    'icon-local-pharmacy' => 'icon-local-pharmacy',
    'icon-local-phone' => 'icon-local-phone',
    'icon-local-pizza' => 'icon-local-pizza',
    'icon-local-play' => 'icon-local-play',
    'icon-local-post-office' => 'icon-local-post-office',
    'icon-local-print-shop' => 'icon-local-print-shop',
    'icon-local-restaurant' => 'icon-local-restaurant',
    'icon-local-see' => 'icon-local-see',
    'icon-local-shipping' => 'icon-local-shipping',
    'icon-local-taxi' => 'icon-local-taxi',
    'icon-location-history' => 'icon-location-history',
    'icon-map' => 'icon-map',
    'icon-navigation' => 'icon-navigation',
    'icon-pin-drop' => 'icon-pin-drop',
    'icon-place' => 'icon-place',
    'icon-rate-review' => 'icon-rate-review',
    'icon-restaurant-menu' => 'icon-restaurant-menu',
    'icon-satellite' => 'icon-satellite',
    'icon-store-mall-directory' => 'icon-store-mall-directory',
    'icon-terrain' => 'icon-terrain',
    'icon-traffic' => 'icon-traffic',
    'icon-apps' => 'icon-apps',
    'icon-arrow-drop-down' => 'icon-arrow-drop-down',
    'icon-arrow-drop-down-circle' => 'icon-arrow-drop-down-circle',
    'icon-arrow-drop-up' => 'icon-arrow-drop-up',
    'icon-arrow-forward2' => 'icon-arrow-forward2',
    'icon-check2' => 'icon-check2',
    'icon-fullscreen' => 'icon-fullscreen',
    'icon-fullscreen-exit' => 'icon-fullscreen-exit',
    'icon-menu' => 'icon-menu',
    'icon-keyboard-control' => 'icon-keyboard-control',
    'icon-more-vert' => 'icon-more-vert',
    'icon-refresh' => 'icon-refresh',
    'icon-unfold-less' => 'icon-unfold-less',
    'icon-unfold-more' => 'icon-unfold-more',
    'icon-adb' => 'icon-adb',
    'icon-bluetooth-audio' => 'icon-bluetooth-audio',
    'icon-disc-full' => 'icon-disc-full',
    'icon-do-not-disturb' => 'icon-do-not-disturb',
    'icon-drive-eta' => 'icon-drive-eta',
    'icon-event-available' => 'icon-event-available',
    'icon-event-busy' => 'icon-event-busy',
    'icon-event-note' => 'icon-event-note',
    'icon-folder-special' => 'icon-folder-special',
    'icon-mms' => 'icon-mms',
    'icon-more' => 'icon-more',
    'icon-network-locked' => 'icon-network-locked',
    'icon-phone-bluetooth-speaker' => 'icon-phone-bluetooth-speaker',
    'icon-phone-forwarded' => 'icon-phone-forwarded',
    'icon-phone-in-talk' => 'icon-phone-in-talk',
    'icon-phone-locked' => 'icon-phone-locked',
    'icon-phone-missed' => 'icon-phone-missed',
    'icon-phone-paused' => 'icon-phone-paused',
    'icon-sd-card' => 'icon-sd-card',
    'icon-sim-card-alert' => 'icon-sim-card-alert',
    'icon-sms' => 'icon-sms',
    'icon-sms-failed' => 'icon-sms-failed',
    'icon-sync' => 'icon-sync',
    'icon-sync-disabled' => 'icon-sync-disabled',
    'icon-sync-problem' => 'icon-sync-problem',
    'icon-system-update' => 'icon-system-update',
    'icon-tap-and-play' => 'icon-tap-and-play',
    'icon-time-to-leave' => 'icon-time-to-leave',
    'icon-vibration' => 'icon-vibration',
    'icon-voice-chat' => 'icon-voice-chat',
    'icon-vpn-lock' => 'icon-vpn-lock',
    'icon-cake' => 'icon-cake',
    'icon-domain' => 'icon-domain',
    'icon-group' => 'icon-group',
    'icon-group-add' => 'icon-group-add',
    'icon-location-city' => 'icon-location-city',
    'icon-mood' => 'icon-mood',
    'icon-notifications' => 'icon-notifications',
    'icon-notifications-none' => 'icon-notifications-none',
    'icon-notifications-off' => 'icon-notifications-off',
    'icon-notifications-paused' => 'icon-notifications-paused',
    'icon-pages' => 'icon-pages',
    'icon-party-mode' => 'icon-party-mode',
    'icon-people' => 'icon-people',
    'icon-people-outline' => 'icon-people-outline',
    'icon-person' => 'icon-person',
    'icon-person-add' => 'icon-person-add',
    'icon-person-outline' => 'icon-person-outline',
    'icon-plus-one' => 'icon-plus-one',
    'icon-poll' => 'icon-poll',
    'icon-public' => 'icon-public',
    'icon-school' => 'icon-school',
    'icon-share' => 'icon-share',
    'icon-whatshot' => 'icon-whatshot',
    'icon-check-box' => 'icon-check-box',
    'icon-check-box-outline-blank' => 'icon-check-box-outline-blank',
    'icon-star' => 'icon-star',
    'icon-star-half' => 'icon-star-half',
    'icon-star-outline' => 'icon-star-outline',
    'icon-account-balance' => 'icon-account-balance',
    'icon-help' => 'icon-help',
    'icon-highlight-remove' => 'icon-highlight-remove',
    'icon-info' => 'icon-info',
    'icon-info-outline' => 'icon-info-outline',
    'icon-label' => 'icon-label',
    'icon-label-outline' => 'icon-label-outline',
    'icon-language' => 'icon-language',
    'icon-query-builder' => 'icon-query-builder',
    'icon-search' => 'icon-search',
    'icon-error' => 'icon-error',
    'icon-warning' => 'icon-warning',
    'icon-report' => 'icon-report',
    'icon-dehaze' => 'icon-dehaze',
    'icon-my-location' => 'icon-my-location',
    'icon-arrow-back' => 'icon-arrow-back',
    'icon-arrow-forward' => 'icon-arrow-forward',
    'icon-cancel' => 'icon-cancel',
    'icon-check' => 'icon-check',
    'icon-chevron-left' => 'icon-chevron-left',
    'icon-chevron-right' => 'icon-chevron-right',
    'icon-close' => 'icon-close',
    'icon-expand-less' => 'icon-expand-less',
    'icon-expand-more' => 'icon-expand-more',
    'icon-linkedin' => 'icon-linkedin',
    'icon-nc-recycle' => 'icon-nc-recycle',
    'icon-nc-nuclear' => 'icon-nc-nuclear',
    'icon-nc-wave' => 'icon-nc-wave',
    'icon-nc-fish' => 'icon-nc-fish',
    'icon-nc-umbrella' => 'icon-nc-umbrella',
    'icon-nc-drinks' => 'icon-nc-drinks',
    'icon-nc-payment-plan' => 'icon-nc-payment-plan',
    'icon-nc-garnishments' => 'icon-nc-garnishments',
    'icon-nc-box' => 'icon-nc-box',
    'icon-nc-motor-carriers' => 'icon-nc-motor-carriers',
    'icon-smoking-rooms' => 'icon-smoking-rooms',
    'icon-child-friendly' => 'icon-child-friendly',
    'icon-opacity' => 'icon-opacity',
    'icon-pets' => 'icon-pets',
    'icon-pregnant-woman' => 'icon-pregnant-woman',
    'icon-motorcycle' => 'icon-motorcycle',
    'icon-child-care' => 'icon-child-care',
    'icon-goat' => 'icon-goat',
    'icon-spa' => 'icon-spa',
    'icon-pool' => 'icon-pool',
    'icon-smoke-free' => 'icon-smoke-free',
    'icon-room-service' => 'icon-room-service',
    'icon-kitchen' => 'icon-kitchen',
    'icon-hot-tub' => 'icon-hot-tub',
    'icon-free-breakfast' => 'icon-free-breakfast',
    'icon-casino' => 'icon-casino',
  );
}
